markdown: kramdown
encoding: utf-8

# Se estiver hospedado em `site.com`, deixe em branco.
# Se estiver em `site.com/exemplo`, dexe `exemplo`.
url_root:

sass:
  style: expanded
  # style: compressed

include:
  - styles/
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
